### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by BitCol** [sclif13/docker-asterisk13-webrtc#1]
Hello, could you please share instructions to run this container ? 

Thanks.

**Comment by sclif13** [comment]
Hello.
1. Download ready image from hub.docker.com
`docker pull sclif13/docker-asterisk13-webrtc`
2. Create docker container
`docker run -d -t --name=asterisk -p 5060:5060/udp
       -p 10000-10200:10000-10200/udp 
       -p 8088:8088 
       -v /data/etc/asterisk:/etc/asterisk 
       sclif13/docker-asterisk13-webrtc`

Ports -p:
- 5060 - sip UDP port
 - 10000 - 10200 - RTP
 - 8088 - Webrtc

If you need to start a container with all ports, use --network host
`docker run -d -t --name=asterisk  --network host -v /data/etc/asterisk:/etc/asterisk 
       sclif13/docker-asterisk13-webrtc`
